### ISSUE TITLE
Only downloads photos in Twitter

### ISSUE THREAD

**Issue by Purefreeman** [elvisyjlin/media-scraper#3]
As stated in the title, i can only download pictures. i download 4 different accounts and it still has the same result

**Comment by elvisyjlin** [comment]
Yes, as stated in the [README](https://github.com/elvisyjlin/media-scraper#twitter), `media-scraper` cannot download the *BLOB URL* videos in Twitter currently. I'll keep working on it but no guarantee when to complete.

**Comment by Purefreeman** [comment]
Ok, sorry for the misunderstanding

**Comment by elvisyjlin** [comment]
Could you please provide an example Twitter username so that I can reproduce the problem and fix it? I've tested `media-scraper` on the Twitter account `realDonaldTrump` which contains a bunch of photos and videos.

**Comment by elvisyjlin** [comment]
I've updated it to handle the json parsing exception. Please take a look.

**Comment by Purefreeman** [comment]
Yes it seems to be working. But it doesn't download some gifs

**Comment by elvisyjlin** [comment]
Could you give me an example? In my observation, the gifs are rendered as mp4s in Twitter posts and they are crawled and downloaded by `mediascraper`.

**Comment by Purefreeman** [comment]
I can't seem to find a good account to show this or recreate it. Thanks
